### PR TITLE
fixed migrationhierarchy secondaryroot validation

### LINKED ISSUE #105: do not validate secondary root in migrationhierarchy when the root namespace is involved
/kind bug

### PR DESCRIPTION
**Pull request by mzeevi**
FIxes #105. With this PR, secondary roots are now validated only when the root namespace is not in place, similar to UpdateQuota

### CODE REVIEW

File: internals/webhooks/validate/migrationhierarchy/migrationhierarchy_create.go [hunk 1]
```diff
@@ -60,6 +60,14 @@ func (a *MigrationHierarchyAnnotator) handleCreate(mhObject *utils.ObjectContext
 		return response
 	}
 
+	// validate the source and destination namespaces are under the same secondary root only
+	// if you are not trying to move rmigrater to the root namespace of the cluster
```
Comment (liadlauber) [inline internals/webhooks/validate/migrationhierarchy/migrationhierarchy_create.go:64]: typo

**Review by liadlauber — COMMENTED** [review]
looks good overall, fix the typo and resumbit.

**Review by liadlauber — APPROVED** [review]
/lgtm
