### PR TITLE
fixed update of descendant subnamespace in migrationhierarchy

### LINKED ISSUE #51: fixed update of descendant subnamespace in migrationhierarchy
When doing MigrationHierarchy, the display-name of the children subnamespace are updated to match the new subnamespace created for the migration. However, there's a bug that causes only the first subnamespace to be updated properly while the others are not updated well.

/kind bug
/assign @omer5yerushalmi

### PR DESCRIPTION
**Pull request by omer5yerushalmi**
Fixes #51. With this PR, the subnamespaces in the hierarchy under the subnamespace that gets migrated are now all updated properly with correct DisplayName. Previously, only the first child subnamespace of the subnamespace that got migrated was being updated correctly.

### CODE REVIEW

File: internals/utils/helper.go [hunk 1]
```diff
@@ -224,6 +224,26 @@ func UpdateAllNsChildsOfNs(nsparent *ObjectContext) error {
...
+	}
+	for _, snsItem := range subspaceChilds.Objects.(*danav1.SubnamespaceList).Items {
+		sns, _ := NewObjectContext(rootObject.Ctx, rootObject.Log, rootObject.Client, types.NamespacedName{Name: snsItem.GetName(), Namespace: snsItem.GetNamespace()}, &danav1.Subnamespace{})
+		childrenNs := GetAllSnsChilds(sns)
+		subspaceDescendant = append(subspaceDescendant, childrenNs...)
+	}
+
+	return append([]*ObjectContext{rootObject}, subspaceDescendant...)
+}
+
```
Comment (mzeevi) [inline internals/utils/helper.go:246]: There's duplicate implementation of this logic here and in `UpdateAllNsChildsOfNs`. You need to update the logic so that `UpdateAllNsChildsOfNs` does not go over the children as well, but instead uses the outout of `GetAllSnsChildren`.

Also `Childs` is not a word, use `Children`

File: internals/controllers/migrationhierarchy_controller.go [hunk 2]
```diff
@@ -145,6 +146,17 @@ func (r *MigrationHierarchyReconciler) Reconcile(ctx context.Context, req ctrl.R
 
 		// resync for the parent source sns
 		r.addSnsToSnsEvent(sourceSnsParentName, sourceSnsParentNamespace)
+
+		// the root sns for resync every sns childrens displayname
+		snsToSync, err := utils.NewObjectContext(ctx, log, r.Client, client.ObjectKey{Name: ns.GetName(), Namespace: utils.GetNamespaceParent(ns.Object)}, &danav1.Subnamespace{})
+		if err != nil {
+			return ctrl.Result{}, err
+		}
```
Comment (mzeevi) [inline internals/controllers/migrationhierarchy_controller.go:154]: I don't understand the comment. Also, don't we already have this object elsewhere in the function?

**Review by mzeevi — APPROVED** [review]
