### PR TITLE
fixes update quota problem that makes resource stuck

### LINKED ISSUE #27: fix updatequota issue causing resources to not propage properly
There is an issue when the API Server is slow where UpdateQuota fails "in the middle" of the operation, because the update of subnamespaces does not:

1. Happen fast enough
2. Happens in a sequential order (due to the nature of reconciliation)

/kind bug

### PR DESCRIPTION
**Pull request by liadlauber**
Fixes #27. With this commit we now check in a loop if the subnamespace has been properly and fully updated before doing the entire updatequota operation. In essence this makes the reconciliation of the subnamespaces involved in the updatequota to be sequential instead of random, which caused an issue with updatequota failing.

### CODE REVIEW

File: internals/controllers/updatequota_controller.go [hunk 1]
```diff
@@ -237,24 +234,32 @@ func subSnsQuota(sns *utils.ObjectContext, quotaSpec corev1.ResourceQuotaSpec) e
...
+// has been properly updated before doing the updatequota operation
+func ensureSnsEqualQuota(sns *utils.ObjectContext) error {
+	ok := false
+	for !ok {
+		quotaObj, err := utils.GetSNSQuotaObj(sns)
+		if err != nil {
+			return err
+		}
+		resourceQuotaSpec := utils.GetQuotaObjSpec(quotaObj.Object)
+		snsQuotaSpec := sns.Object.(*danav1.Subnamespace).Spec.ResourceQuotaSpec
```
Comment (mzeevi) [inline internals/controllers/updatequota_controller.go:255]: This doesn't need to be inside the loop since it doesn't change between iterations

File: internals/controllers/updatequota_controller.go [hunk 2]
```diff
@@ -237,24 +234,32 @@ func subSnsQuota(sns *utils.ObjectContext, quotaSpec corev1.ResourceQuotaSpec) e
...
+		for res := range resourceQuotaSpec.Hard {
+			if snsQuotaSpec.Hard[res] != resourceQuotaSpec.Hard[res] {
 				ok = false
 			}
 		}
+		ok = true
+		time.Sleep(500 * time.Millisecond)
```
Comment (mzeevi) [inline internals/controllers/updatequota_controller.go:262]: Add a short comment explaining why there's a need for the sleep

**Comment by mzeevi** [comment]
Just fix as per the comments I left above and amend the commit message

/lgtm

File: internals/controllers/updatequota_controller.go [hunk 3]
```diff
@@ -237,24 +234,33 @@ func subSnsQuota(sns *utils.ObjectContext, quotaSpec corev1.ResourceQuotaSpec) e
...
+// ensureSnsEqualQuota compares the sns quota spec and the resource quota spec
+// in a loop until they are equal. this way we can know that the subnamespace
+// has been properly updated before doing the updatequota operation
+func ensureSnsEqualQuota(sns *utils.ObjectContext) error {
+	ok := false
+	quotaObj, err := utils.GetSNSQuotaObj(sns)
+	if err != nil {
+		return err
+	}
+	resourceQuotaSpec := utils.GetQuotaObjSpec(quotaObj.Object)
```
Comment (mzeevi) [inline internals/controllers/updatequota_controller.go:253]: This does need to be inside the while loop since we need to fetch the new object everytime to make sure it's been updated properly

**Review by mzeevi — APPROVED** [review]
